name: Next.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [22.19.0]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

  
      - name: Install dependencies
        run: npm i --force

      - name: Build Next.js app
        run: npm run build

      - name: Upload production build (optional)
        uses: actions/upload-artifact@v4
        with:
          name: next-build
          path: .next
